### PR TITLE
chore(lint): upgrades and new checks

### PR DESCRIPTION
**Pull request by ygworldr**
### For developers

More `ruff` checks.

## FlowFast

N.A.

### CODE REVIEW

**Comment by ygworldr** [comment]
CodeQL is picking all our dependencies. This is irritating…

**Comment by ygworldr** [comment]
@felickz Not sure if you can see this one… The errors are back. What am I missing?

**Comment by felickz** [comment]
> @felickz Not sure if you can see this one… The errors are back. What am I missing?

👋 This branch doesnt have the changes from #84 merged in ... `setup-python-dependencies: false` is the important piece from [here](https://github.com/worldr/setupr/pull/84/files#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27R56-R58)

**Comment by felickz** [comment]
> @felickz Not sure if you can see this one… The errors are back. What am I missing?

👋 @ygworldr - acknowledging here I can see that the venv creation is leading to this behavior.  I have recreated your scenario and I am further following up to see if there is anything that can be done to properly exclude dependencies as you have attempted in the config file.  [Dismissing them after detection](https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository#dismissing--alerts) is one possibility, but that will be our last resort.  Thanks for your patience 🙇

**Comment by ygworldr** [comment]
> > @felickz Not sure if you can see this one… The errors are back. What am I missing?
> 
> wave @ygworldr - acknowledging here I can see that the [venv creation](https://github.com/worldr/setupr/pull/83/files#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27R58) inside [the project](https://github.com/worldr/setupr/blob/chore/upgrades/poetry.toml#L2) + [configuration](https://github.com/worldr/setupr/blob/chore/upgrades/.github/workflows/setup-poetry-env/action.yml#L30) is leading to this behavior. I have recreated your scenario and I am further following up to see if there is anything that can be done to properly exclude dependencies as you have attempted in the config file. [Dismissing them after detection](https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository#dismissing--alerts) is one possibility or [filtering the SARIF output](https://github.com/advanced-security/filter-sarif) but that will be our last resort. Thanks for your patience bow

Thank you very much for your efforts. It is much appreciated.

**Review by yellowmegaman — APPROVED** [review]
LGTM

**Comment by ygworldr** [comment]
> @felickz
>  […] [filtering the SARIF output](https://github.com/advanced-security/filter-sarif) but that will be our last resort.

Well, filtering the SARIF file seems to have done it. It is not elegant, but works.

**Comment by felickz** [comment]
> > @felickz
> > […] [filtering the SARIF output](https://github.com/advanced-security/filter-sarif) but that will be our last resort.
> 
> Well, filtering the SARIF file seems to have done it. It is not elegant, but works.

Awesome you were able to plug that in :) happy we had a workaround.  Good news - product has implemented a fix ... i submitted a PR for your review: #89 89

**Pull request merged**
